/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
// };

module.exports = {
  docs: [
    "intro",
    {
      type: "category",
      label: "PWmat",
      // link: {
      //   type: "doc",
      //   id: "Q-Studio/README",
      // },
      collapsible: true,
      collapsed: true,
      items: [
        "PWmat/download",
        "PWmat/Installation",
        "PWmat/Manual",
        "PWmat/Input",
        "PWmat/Output",
        {
          type: "category",
          label: "Examples",
          items: [
            "PWmat/scf",
            "PWmat/dos",
            "PWmat/Bandsctructure",
            "PWmat/HSEscf",
            "PWmat/HSEband",
            "PWmat/Structure Optimization",
            "PWmat/Structure Optimization2",
            "PWmat/HSE Relaxation",
            "PWmat/Charge system relaxation",
            "PWmat/md",
            "PWmat/spin",
            "PWmat/soc",
            "PWmat/soc_nolinear",
            "PWmat/u",
            "PWmat/dipole1",
            "PWmat/dipole2",
            "PWmat/neb",
            "PWmat/Dimer",
          ],
        },
        {
          type: "category",
          label: "Modules",
          link: {
            type: "doc",
            id: "PWmat/Module/README",
          },
          items: [
            "PWmat/Module/1",
            "PWmat/Module/2",
            "PWmat/Module/4",
            "PWmat/Module/15",
            "PWmat/Module/17",
            "PWmat/Module/18",
            "PWmat/Module/74",
          ],
        },
        // "PWmat/Script",
      ],
    },
    {
      type: "category",
      label: "MLFF",
      link: {
        type: "doc",
        id: "MLFF/README",
      },
      collapsible: true,
      collapsed: true,
      items: [
        "MLFF/Installation",
        "MLFF/Quickstart",
        "MLFF/Parameter details",
        "MLFF/Appendix-1",
        // {
        //   type: "category",
        //   label: "Quickstart",
        //   items: [
        //     "MLFF/1",
        //     "MLFF/2",
        //     "MLFF/3",
        //   ],
        // },
      ],
    },
    {
      type: "category",
      label: "Q-Studio",
      link: {
        type: "doc",
        id: "Q-Studio/README",
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "界面及功能",
          link: {
            type: "doc",
            id: "Q-Studio/qstudio_main",
          },
          items: [
            {
              type: "category",
              label: "菜单",
              link: {
                type: "doc",
                id: "Q-Studio/qstudio_manual",
              },
              items: [    
                "Q-Studio/qstudio_manual_file",
                "Q-Studio/qstudio_manual_edit",
                "Q-Studio/qstudio_manual_view",
                "Q-Studio/qstudio_manual_setting",
                "Q-Studio/qstudio_manual_build",
                "Q-Studio/qstudio_manual_select",
              ],
            },
            "Q-Studio/qstudio_structtools",
            "Q-Studio/qstudio_visiontools",
            "Q-Studio/qstudio_navigation",
            "Q-Studio/qstudio_visualization",
            "Q-Studio/qstudio_property",
            "Q-Studio/qstudio_addgroup",
          ],
        },
        {
          type: "category",
          label: "建模示例",
          link: {
            type: "doc",
            id: "Q-Studio/qstudio_example",
          },
          items: [
            "Q-Studio/qstudio_example_crystal",
            "Q-Studio/qstudio_example_surface",
            "Q-Studio/qstudio_example_2d",
            "Q-Studio/qstudio_example_hetero",
            "Q-Studio/qstudio_example_moire",
            "Q-Studio/qstudio_example_mol",
            "Q-Studio/qstudio_example_transport",
            "Q-Studio/qstudio_example_neb",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Q-Flow",
      link: {
        type: "doc",
        id: "Q-Flow/README",
      },
      collapsible: true,
      collapsed: true,
      items: [
        "Q-Flow/login",
        "Q-Flow/创建",
        {
          type: "category",
          label: "组件",
          // link: {
          //   type: "doc",
          //   id: "Q-Flow/chapter_1",
          // },
          items: [
            "Q-Flow/chapter_31",
            "Q-Flow/chapter_32",
            "Q-Flow/chapter_33",
            "Q-Flow/chapter_34",
            "Q-Flow/chapter_35",
            "Q-Flow/chapter_36",
            "Q-Flow/chapter_37",
            "Q-Flow/chapter_38",
            "Q-Flow/chapter_39",
          ],
        },
        "Q-Flow/chapter_4",
        {
          type: "category",
          label: "计算示例",
          items: [
            "Q-Flow/chapter_51",
            "Q-Flow/chapter_52",
            "Q-Flow/chapter_53",
            "Q-Flow/chapter_54",
            "Q-Flow/chapter_55",
            "Q-Flow/chapter_56",
            "Q-Flow/chapter_57",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "PWkit",
      link: {
        type: "doc",
        id: "PWkit/README",
      },
      collapsible: true,
      collapsed: true,
      items: [
        "PWkit/下载与安装",
        "PWkit/使用示例",
      ],
    },
  ],
};