/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
// };

module.exports = {
  docs: [
    "intro",
    {
      type: "category",
      label: "PWmat",
      // link: {
      //   type: "doc",
      //   id: "Q-Studio/README",
      // },
      collapsible: true,
      collapsed: true,
      items: [
        "PWmat/download",
        "PWmat/Installation",
        "PWmat/Manual",
        "PWmat/Input",
        "PWmat/Output",
        {
          type: "category",
          label: "Examples",
          items: [
            "PWmat/scf",
            "PWmat/dos",
            "PWmat/Bandsctructure",
            "PWmat/HSEscf",
            "PWmat/HSEband",
            "PWmat/Structure Optimization",
            "PWmat/Structure Optimization2",
            "PWmat/HSE Relaxation",
            "PWmat/Charge system relaxation",
            "PWmat/md",
            "PWmat/spin",
            "PWmat/soc",
            "PWmat/soc_nolinear",
            "PWmat/u",
            "PWmat/dipole1",
            "PWmat/dipole2",
            "PWmat/neb",
            "PWmat/Dimer",
          ],
        },
        {
          type: "category",
          label: "Modules",
          link: {
            type: "doc",
            id: "PWmat/Module/README",
          },
          items: [
            "PWmat/Module/1",
            "PWmat/Module/2",
            "PWmat/Module/3",
            "PWmat/Module/4",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Q-Studio",
      link: {
        type: "doc",
        id: "Q-Studio/README",
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "1. 界面介绍及功能",
          link: {
            type: "doc",
            id: "Q-Studio/chapter_1",
          },
          items: [
            "Q-Studio/chapter_11",
            "Q-Studio/chapter_12",
            "Q-Studio/chapter_13",
            "Q-Studio/chapter_14",
            "Q-Studio/chapter_15",
            "Q-Studio/chapter_16",
            "Q-Studio/chapter_17",
          ],
        },
        {
          type: "category",
          label: "2. 建模示例",
          link: {
            type: "doc",
            id: "Q-Studio/chapter_2",
          },
          items: [
            "Q-Studio/chapter_21",
            "Q-Studio/chapter_22",
            "Q-Studio/chapter_23",
            "Q-Studio/chapter_24",
            "Q-Studio/chapter_25",
            "Q-Studio/chapter_26",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Q-Flow",
      link: {
        type: "doc",
        id: "Q-Flow/README",
      },
      collapsible: true,
      collapsed: true,
      items: [
        "Q-Flow/login",
        "Q-Flow/创建",
        {
          type: "category",
          label: "组件",
          // link: {
          //   type: "doc",
          //   id: "Q-Flow/chapter_1",
          // },
          items: [
            "Q-Flow/chapter_31",
            "Q-Flow/chapter_32",
            "Q-Flow/chapter_33",
            "Q-Flow/chapter_34",
            "Q-Flow/chapter_35",
            "Q-Flow/chapter_36",
            "Q-Flow/chapter_37",
            "Q-Flow/chapter_38",
            "Q-Flow/chapter_39",
          ],
        },
        "Q-Flow/chapter_4",
        {
          type: "category",
          label: "计算示例",
          items: [
            "Q-Flow/chapter_51",
            "Q-Flow/chapter_52",
            "Q-Flow/chapter_53",
            "Q-Flow/chapter_54",
            "Q-Flow/chapter_55",
            "Q-Flow/chapter_56",
            "Q-Flow/chapter_57",
          ],
        },
      ],
    },
    "PWkit",
  ],
};